ChartValues:
  dataset:
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
      limits:
        memory: 512Mi
        cpu: 1000m
HelmChartPath: helm
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: workhardliuzheng/quickstart-fuild
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: workhardliuzheng
Branch: main
Platform: github
